In [1]:
#NumPy Exercises

In [2]:
#Import NumPy as np
import numpy as np

In [3]:
#Create an array of 10 zeros
arr = np.zeros(10)

In [4]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#Create an array of 10 ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#Create an array of 10 fives
arr = np.array([5]*10)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [7]:
#Create an array of the integers from 10 to 50
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
#Create an array of all the even integers from 10 to 50
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
#Create a 3x3 matrix with values ranging from 0 to 8
arr = np.array([[0,1,2],[3,4,5],[6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#Create a 3x3 identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
#Use NumPy to generate a random number between 0 and 1
arr = np.random.randint(0,1)
arr

0

In [13]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
arr = np.random.randint(26)
arr

15

In [14]:
#Create the following matrix:
arr=np.linspace(0,1,100)
arr
array = arr.reshape(10,10)
array

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [15]:
#Create an array of 20 linearly spaced points between 0 and 1:


In [16]:
array = np.linspace(0,1,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [17]:
#Numpy Indexing and Selection

In [18]:
#Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:



In [19]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat = np.arange(14,26).reshape(3,4)
mat

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [22]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [23]:
mat[1:2,2:3]

array([[20]])

In [24]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [25]:
mat = np.arange(1,26).reshape(5,5)
mat
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [26]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat
mat[4:5,0:5]

array([[21, 22, 23, 24, 25]])

In [28]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
mat[3:5,0:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
#Now do the following
#Get the sum of all the values in mat

In [31]:
mat = np.arange(1,26).reshape(5,5)
mat
total_sum = np.sum(mat)
total_sum

325

In [32]:
#Get the standard deviation of the values in mat


In [33]:
std = np.std(mat)
std

7.211102550927978

In [34]:
#Get the sum of all the columns in mat

In [35]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
mat1 = np.sum(mat[0:5,0:1])
mat1

55

In [37]:
mat2=np.sum(mat[0:5,1:2])
mat2

60

In [38]:
mat3 = np.sum(mat[0:5,2:3])
mat3

65

In [39]:
mat4 = np.sum(mat[0:5,3:4])
mat4

70

In [40]:
mat5 = np.sum(mat[0:5,4:5])
mat5

75

In [41]:
arr = np.array([mat1,mat2,mat3,mat4,mat5])

In [42]:
arr

array([55, 60, 65, 70, 75])